# -*- coding: utf-8 -*-
"""
golazox — configuration, products, clubs, size chart, rewards, translations.
"""
import os

# ============================== STORE CONFIG ==============================
WHATSAPP = os.environ.get("WHATSAPP", "97338818226")
ADMIN_PASS = os.environ.get("ADMIN_PASS", "golazox2026")
ADMIN_EMAIL = "golazox22@gmail.com"
ADMIN_QUESTION = "أفضل شخص مين؟"
ADMIN_ANSWER = "احمد الشيخ"
CURRENCY_AR = "د.ب"
CURRENCY_EN = "BHD"
PRICE_JERSEY = 7.0
PRICE_MUG = 6.0
DELIVERY_FEE = 2.0
ORDER_PREFIX = "GX"
POINTS_PER_BHD = 1.0

# ============================== SIZE CHART (cm) ==============================
SIZE_ORDER = ["S", "M", "L", "XL", "2XL", "3XL"]
SIZE_CHART = {
    "S":   {"length": "69",       "width": "49–51",   "height": "162–170", "weight": "52–62"},
    "M":   {"length": "69–71",    "width": "51–53",   "height": "170–176", "weight": "62–78"},
    "L":   {"length": "71–73",    "width": "53–55",   "height": "176–182", "weight": "78–83"},
    "XL":  {"length": "73–75",    "width": "55–57",   "height": "182–190", "weight": "83–90"},
    "2XL": {"length": "75–77",    "width": "57–59",   "height": "190–195", "weight": "90–97"},
    "3XL": {"length": "77–79",    "width": "59–61",   "height": "195–200", "weight": "97–105"},
}
MUG_SIZE = "OS"

# ============================== CLUBS (themes) ==============================
CLUBS = {
    "arsenal": {"ar": "أرسنال",          "en": "Arsenal",             "accent": "#EF0107", "accent2": "#9E0000", "emoji": "🔴"},
    "liver":   {"ar": "ليفربول",         "en": "Liverpool",           "accent": "#C8102E", "accent2": "#7A0C20", "emoji": "🔴"},
    "nassr":   {"ar": "النصر",           "en": "Al-Nassr",            "accent": "#F7D033", "accent2": "#1B1B1B", "emoji": "🟡"},
    "bayern":  {"ar": "بايرن ميونخ",     "en": "Bayern Munich",       "accent": "#DC052D", "accent2": "#8E0A22", "emoji": "🔴"},
    "united":  {"ar": "مانشستر يونايتد", "en": "Manchester United",   "accent": "#DA291C", "accent2": "#5E0F0A", "emoji": "🔴"},
    "city":    {"ar": "مانشستر سيتي",    "en": "Manchester City",     "accent": "#6CABDD", "accent2": "#1C2C5B", "emoji": "🔷"},
    "juve":    {"ar": "يوفنتوس",         "en": "Juventus",            "accent": "#111111", "accent2": "#5B5B5B", "emoji": "⚫"},
    "barca":   {"ar": "برشلونة",        "en": "Barcelona",           "accent": "#A50044", "accent2": "#004D98", "emoji": "🔵"},
    "real":    {"ar": "ريال مدريد",     "en": "Real Madrid",         "accent": "#C9A24B", "accent2": "#1F3864", "emoji": "🤍"},
    "green":   {"ar": "الأخضر والأبيض", "en": "Green & White",       "accent": "#1B7A3D", "accent2": "#0E4D26", "emoji": "🟢"},
    "psg":     {"ar": "باريس سان جيرمان", "en": "Paris Saint-Germain", "accent": "#004170", "accent2": "#DA291C", "emoji": "🔵"},
    "hilal":   {"ar": "الهلال",         "en": "Al-Hilal",            "accent": "#1E4FA3", "accent2": "#0C2D6E", "emoji": "🔵"},
}

# ============================== CLUB THEMES (dynamic, admin-editable) ==============================
# Each club maps to site accent colors: ac (primary), ac2 (secondary gradient),
# glow (hex used for the button shadow), tint (hex used for the subtle background wash).
# Admins can override these in the dashboard; overrides persist in the DB.
CLUB_THEMES = {
    "arsenal": {"ac": "#EF0107", "ac2": "#9E0000", "glow": "#EF0107", "tint": "#EF0107"},
    "liver":   {"ac": "#C8102E", "ac2": "#7A0C20", "glow": "#C8102E", "tint": "#C8102E"},
    "nassr":   {"ac": "#F7D033", "ac2": "#1B1B1B", "glow": "#F7D033", "tint": "#F7D033"},
    "bayern":  {"ac": "#DC052D", "ac2": "#8E0A22", "glow": "#DC052D", "tint": "#DC052D"},
    "united":  {"ac": "#DA291C", "ac2": "#5E0F0A", "glow": "#DA291C", "tint": "#DA291C"},
    "city":    {"ac": "#1C2C5B", "ac2": "#6CABDD", "glow": "#6CABDD", "tint": "#6CABDD"},
    "juve":    {"ac": "#111111", "ac2": "#5B5B5B", "glow": "#111111", "tint": "#111111"},
    "barca":   {"ac": "#A50044", "ac2": "#004D98", "glow": "#A50044", "tint": "#004D98"},
    "real":    {"ac": "#C9A24B", "ac2": "#1F3864", "glow": "#C9A24B", "tint": "#C9A24B"},
    "green":   {"ac": "#1B7A3D", "ac2": "#0E4D26", "glow": "#1B7A3D", "tint": "#1B7A3D"},
    "psg":     {"ac": "#004170", "ac2": "#DA291C", "glow": "#004170", "tint": "#004170"},
    "hilal":   {"ac": "#1E4FA3", "ac2": "#0C2D6E", "glow": "#1E4FA3", "tint": "#1E4FA3"},
}

# ============================== PRODUCTS ==============================
# stock: jersey -> {size: qty}; mug -> {OS: qty}. Admin panel overrides via DB.
# badges: "new" | "best" | "offer" | "soldout" (soldout computed from stock too)
DEFAULT_JERSEY_STOCK = {"S": 3, "M": 5, "L": 8, "XL": 4, "2XL": 2, "3XL": 0}

PRODUCTS = [
    # ---- جيرسيات الأندية (10 أندية، صور حقيقية في static/img) ----
    {"id": "j1", "kind": "jersey", "club_id": "real", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت ريال مدريد — الأساسي", "name_en": "Real Madrid Home Jersey",
     "desc_ar": "القميص الأساسي لريال مدريد 2025/2026. قماش رياضي خفيف ومريح بتهوية ممتازة.", "desc_en": "Real Madrid home jersey 2025/2026. Light, breathable athletic fabric.",
     "colors": ["#F8F9FA", "#C9A24B"], "emoji": "👕", "imgs": ["j1_1"],
     "badges": ["best"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j13", "kind": "jersey", "club_id": "real", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت ريال مدريد — الاحتياطي", "name_en": "Real Madrid Away Jersey",
     "desc_ar": "القميص الاحتياطي الأزرق الداكن لريال مدريد. خامة رياضية فاخرة.", "desc_en": "Real Madrid away jersey in dark navy. Premium athletic fabric.",
     "colors": ["#1F3864", "#C9A24B"], "emoji": "👕", "imgs": ["j13_1"],
     "badges": ["new"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j2", "kind": "jersey", "club_id": "barca", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت برشلونة", "name_en": "Barcelona Jersey",
     "desc_ar": "قميص برشلونة الأسود والبنفسجي 2025/2026. قماش رياضي خفيف ومريح.", "desc_en": "Barcelona black & purple jersey 2025/2026. Light athletic fabric.",
     "colors": ["#002D72", "#A50044"], "emoji": "👕", "imgs": ["j2_1"],
     "badges": [], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j3", "kind": "jersey", "club_id": "liver", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت ليفربول", "name_en": "Liverpool Jersey",
     "desc_ar": "قميص ليفربول الأخضر/الأزرق الداكن 2025/2026. خامة رياضية عالية الجودة.", "desc_en": "Liverpool green/dark blue jersey 2025/2026. High-quality athletic fabric.",
     "colors": ["#0F3B45", "#7A0C20"], "emoji": "👕", "imgs": ["j3_1"],
     "badges": ["offer"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j4", "kind": "jersey", "club_id": "city", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت مانشستر سيتي", "name_en": "Manchester City Jersey",
     "desc_ar": "قميص مانشستر سيتي السماوي 2025/2026. قماش رياضي خفيف ومريح.", "desc_en": "Manchester City sky-blue jersey 2025/2026. Light athletic fabric.",
     "colors": ["#6CABDD", "#1C2C5B"], "emoji": "👕", "imgs": ["j4_1"],
     "badges": [], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j6", "kind": "jersey", "club_id": "nassr", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت النصر", "name_en": "Al-Nassr Jersey",
     "desc_ar": "قميص النصر الأبيض والذهبي 2025/2026. خامة رياضية فاخرة ومريحة.", "desc_en": "Al-Nassr white & gold jersey 2025/2026. Premium athletic fabric.",
     "colors": ["#F7D033", "#1B1B1B"], "emoji": "👕", "imgs": ["j6_1"],
     "badges": [], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j7", "kind": "jersey", "club_id": "arsenal", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت أرسنال", "name_en": "Arsenal Jersey",
     "desc_ar": "قميص أرسنال الأحمر الكلاسيكي 2025/2026. قماش رياضي خفيف ومريح.", "desc_en": "Classic red Arsenal jersey 2025/2026. Light athletic fabric.",
     "colors": ["#EF0107", "#9E0000"], "emoji": "👕", "imgs": ["j7_1"],
     "badges": ["best"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j14", "kind": "jersey", "club_id": "arsenal", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت أرسنال — الإصدار الأحمر", "name_en": "Arsenal Red Edition Jersey",
     "desc_ar": "إصدار أحمر خاص من قميص أرسنال. تصميم مميز وخامة رياضية عالية الجودة.", "desc_en": "Special red edition Arsenal jersey. Distinct design, premium athletic fabric.",
     "colors": ["#D4000F", "#7A0C20"], "emoji": "👕", "imgs": ["j14_1"],
     "badges": ["new"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j8", "kind": "jersey", "club_id": "bayern", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت بايرن ميونخ", "name_en": "Bayern Munich Jersey",
     "desc_ar": "قميص بايرن ميونخ الأحمر 2025/2026. قماش رياضي خفيف ومريح.", "desc_en": "Bayern Munich red jersey 2025/2026. Light athletic fabric.",
     "colors": ["#DC052D", "#8E0A22"], "emoji": "👕", "imgs": ["j8_1"],
     "badges": ["best"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j9", "kind": "jersey", "club_id": "united", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت مانشستر يونايتد", "name_en": "Manchester United Jersey",
     "desc_ar": "قميص مانشستر يونايتد الأحمر 2025/2026. خامة رياضية فاخرة.", "desc_en": "Manchester United red jersey 2025/2026. Premium athletic fabric.",
     "colors": ["#DA291C", "#5E0F0A"], "emoji": "👕", "imgs": ["j9_1"],
     "badges": ["new"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j10", "kind": "jersey", "club_id": "juve", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت يوفنتوس", "name_en": "Juventus Jersey",
     "desc_ar": "قميص يوفنتوس الأبيض والأسود 2025/2026. تصميم السيدة العجوز الكلاسيكي.", "desc_en": "Juventus white & black jersey 2025/2026, the Old Lady classic.",
     "colors": ["#111111", "#5B5B5B"], "emoji": "👕", "imgs": ["j10_1"],
     "badges": [], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j12", "kind": "jersey", "club_id": "psg", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت باريس سان جيرمان", "name_en": "PSG Jersey",
     "desc_ar": "قميص باريس سان جيرمان الأزرق والأحمر 2025/2026. قماش رياضي خفيف ومريح.", "desc_en": "PSG blue & red jersey 2025/2026. Light athletic fabric.",
     "colors": ["#004170", "#DA291C"], "emoji": "👕", "imgs": ["j12_1"],
     "badges": ["best"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j5", "kind": "jersey", "club_id": "hilal", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت الهلال", "name_en": "Al-Hilal Jersey",
     "desc_ar": "قميص الهلال الأزرق الرسمي. قماش رياضي خفيف ومريح.", "desc_en": "Official Al-Hilal blue jersey. Light athletic fabric.",
     "colors": ["#1E4FA3", "#0C2D6E"], "emoji": "👕", "imgs": ["j5_1"],
     "badges": ["new"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    {"id": "j11", "kind": "jersey", "club_id": "green", "price": PRICE_JERSEY,
     "name_ar": "تيشيرت الأخضر والأبيض", "name_en": "Green & White Jersey",
     "desc_ar": "قميص الأخضر والأبيض الرسمي. قماش رياضي خفيف ومريح.", "desc_en": "Official Green & White jersey. Light athletic fabric.",
     "colors": ["#1B7A3D", "#0E4D26"], "emoji": "👕", "imgs": ["j11_1"],
     "badges": ["new"], "stock": dict(DEFAULT_JERSEY_STOCK)},
    # ---- المقّات ----
    {"id": "m1", "kind": "mug", "price": PRICE_MUG,
     "name_ar": "مق كأس العالم", "name_en": "World Cup Mug",
     "desc_ar": "مق سيراميك فاخر بتصميم كأس العالم.", "desc_en": "Premium ceramic mug, World Cup design.",
     "colors": ["#1B1B1B", "#C9A24B"], "emoji": "☕", "imgs": ["m1_1"],
     "badges": [], "stock": {MUG_SIZE: 10}},
    {"id": "m2", "kind": "mug", "price": PRICE_MUG,
     "name_ar": "مق الكرة", "name_en": "Football Mug",
     "desc_ar": "مق سيراميك بشكل كرة القدم.", "desc_en": "Football-shaped ceramic mug.",
     "colors": ["#C8102E", "#7A0C20"], "emoji": "☕", "imgs": ["m2_1"],
     "badges": ["best"], "stock": {MUG_SIZE: 8}},
    {"id": "m3", "kind": "mug", "club_id": "real", "price": PRICE_MUG,
     "name_ar": "مق ريال مدريد", "name_en": "Real Madrid Mug",
     "desc_ar": "مق بشعار ريال مدريد.", "desc_en": "Real Madrid branded mug.",
     "colors": ["#F8F9FA", "#C9A24B"], "emoji": "☕", "imgs": ["m3_1"],
     "badges": ["new"], "stock": {MUG_SIZE: 6}},
    {"id": "m4", "kind": "mug", "club_id": "hilal", "price": PRICE_MUG,
     "name_ar": "مق الهلال", "name_en": "Al-Hilal Mug",
     "desc_ar": "مق بشعار الهلال.", "desc_en": "Al-Hilal branded mug.",
     "colors": ["#1E4FA3", "#0C2D6E"], "emoji": "☕", "imgs": ["m4_1"],
     "badges": [], "stock": {MUG_SIZE: 12}},
]

# ============================== REWARDS (GOAL POINTS) ==============================
REWARDS = [
    {"points": 5,   "ar": "خصم 1 د.ب",       "en": "1 BHD off",       "discount": 1.0},
    {"points": 10,  "ar": "خصم 2 د.ب",       "en": "2 BHD off",       "discount": 2.0},
    {"points": 20,  "ar": "هدية مق",         "en": "Free mug",        "discount": 6.0},
    {"points": 30,  "ar": "خصم خاص 4 د.ب",   "en": "4 BHD special off", "discount": 4.0},
]

# ============================== NEW DROP / MATCHDAY (manual config) ==============================
# Set via admin panel or here. Countdown only when set.
DROP = None  # {"ar": "تشكيلة الموسم الجديد", "en": "New Season Collection", "target": "2026-08-15 21:00", "img": "j1_1", "product_ids": ["j1","j2","j3"]}
MATCHES = [
    # {"home": "real", "away": "barca", "kickoff": "2026-08-10 22:00", "result": None}
]
MATCHDAY_START_HOURS = 72   # banner appears this many hours before kickoff
MATCHDAY_END_HOURS = 4      # banner hides this many hours after kickoff

# ============================== TRANSLATIONS ==============================
L = {
    "ar": {
        "nav_home": "الرئيسية", "nav_jerseys": "تيشرتات الأندية", "nav_mugs": "المقّات",
        "nav_sizes": "دليل المقاسات", "nav_order": "طريقة الطلب", "nav_contact": "تواصل معنا",
        "lang_name": "English", "settings_btn": "الإعدادات",
        "set_title": "⚙️ إعدادات الموقع", "set_lang": "🌐 اللغة", "set_theme": "🌙 المظهر",
        "theme_light": "☀️ نهاري", "theme_dark": "🌙 ليلي", "set_font": "🔤 حجم الخط",
        "font_small": "A− صغير", "font_med": "A متوسط", "font_large": "A+ كبير",
        "close": "إغلاق",
        "badge": "متجر تيشرتات الأندية والمقّات الرياضية",
        "hero_t1": "تشكيلة تيشرتات الأندية", "hero_t2": "والمقّات الرياضية",
        "hero_sub": "تشكيلة فخمة ومتجددة من تيشرتات الأندية والمقّات الرياضية بجودة عالية — اطلب الآن.",
        "hero_cta_j": "تسوّق التيشرتات", "hero_cta_m": "شوف المقّات",
        "sec_jerseys": "أحدث التيشيرتات", "sec_jerseys_sub": "تشكيلة موسم 2025/2026 — المقاسات S إلى 3XL",
        "sec_mugs": "المقّات",         "sec_mugs_sub": "6 د.ب فقط",
        "cat_jersey": "تيشيرت النادي", "cat_mug": "مق رياضي",
        "view": "عرض المنتج", "add": "أضف للسلة",
        "price_jersey": "7 د.ب", "price_mug": "6 د.ب",
        "wa_intro": "أريد طلب:",
        "sort_label": "ترتيب حسب:", "sort_new": "الأحدث", "sort_lo": "السعر: من الأقل للأعلى",
        "sort_hi": "السعر: من الأعلى للأقل", "sort_best": "الأكثر مبيعًا",
        "filters_btn": "الفلاتر", "show_all": "عرض جميع التيشيرتات",
        "fp_title": "تصفية المنتجات", "fp_colors": "اللون", "fp_cat": "الأكثر مبيعًا",
        "fp_club": "النادي", "fp_size": "المقاس", "fp_more": "المزيد +",
        "cat_best": "الأكثر مبيعًا", "cat_new": "الجديد", "cat_offer": "الخصومات",
        "show_results": "عرض النتائج 🛒",
        "feat_1_t": "توصيل سريع", "feat_1_d": "إلى كافة مناطق المملكة",
        "feat_2_t": "دفع آمن", "feat_2_d": "خيارات دفع متعددة",
        "feat_3_t": "جودة عالية", "feat_3_d": "خامات أصلية 100%",
        "feat_4_t": "ضمان الاستبدال", "feat_4_d": "استبدال واسترجاع سهل وسريع",
        "b_new": "جديد ✨", "b_best": "الأكثر مبيعًا 🔥", "b_offer": "عرض 🏷️", "b_soldout": "غير متوفر",
        "search_ph": "🔍 ابحث عن نادي أو منتج...",
        "filter_club": "النادي", "filter_type": "نوع المنتج", "filter_size": "المقاس",
        "filter_all": "الكل", "fav_filter": "❤️ المفضلة", "img_search": "📷 ابحث بالصورة",
        "search_none": "ما لقينا المنتج اللي تبحث عنه ⚽", "clear_filters": "مسح الفلاتر",
        "filter_price": "السعر", "price_min": "من", "price_max": "إلى",
        "filter_avail": "المتوفر فقط", "filter_apply": "تطبيق",
        "size_label": "اختر المقاس", "size_guide": "دليل المقاسات",
        "qty_label": "الكمية", "order_wa": "اطلب عبر WhatsApp",
        "size_required": "⚠️ يرجى اختيار المقاس أولًا.",
        "size_oos": "هذا المقاس غير متوفر حاليًا.",
        "notify_me": "🔔 أبلغني عند توفر المقاس",
        "notif_title": "المقاس غير متوفر حاليًا 🔔",
        "notif_sub": "أدخل رقم هاتفك وسنرسل لك إشعارًا فور توفر هذا المقاس.",
        "phone_label": "📱 رقم الهاتف", "country_label": "رمز الدولة",
        "notify_btn": "🔔 أبلغني عند التوفر",
        "notify_ok": "✅ تم تسجيل رقمك بنجاح!",
        "notify_ok2": "سنخبرك فور توفر مقاس {size}.",
        "stock_left": "🔥 باقي {n} فقط", "in_stock": "متوفر الآن ✓",
        "detail_btn": "شوف التفاصيل 🔍",
        "trust_1": "⭐ تقييم ممتاز", "trust_2": "🔥 الأكثر طلبًا", "trust_3": "✓ متوفر الآن", "trust_4": "👕 مقاسات متعددة",
        "trust_i1": "✓ الطلب عبر واتساب", "trust_i2": "✓ دليل مقاسات واضح",
        "trust_i3": "✓ إمكانية الاستبدال حسب الشروط", "trust_i4": "✓ إشعار عند توفر المقاس المنتهي",
        "you_may_like": "قد يعجبك أيضًا ⚽",
        "last_order": "🔄 سبق طلبت هذا المنتج — مقاسك السابق: {sz}، الكمية: {q}",
        "saved_size": "📏 مقاسك المحفوظ لهذا المنتج: {sz}",
        "rat_title": "تقييمات العملاء ⭐", "rat_empty": "لا توجد تقييمات بعد — كن أول من يقيّم!",
        "rat_avg": "{avg} / 5", "rat_based": "بناءً على {n} تقييم",
        "rat_write": "✍️ اكتب تقييمك", "rat_name": "اسمك", "rat_stars": "التقييم",
        "rat_comment": "تعليقك", "rat_photo": "📷 صورة (اختياري)",
        "rat_submit": "نشر التقييم", "rat_thanks": "✅ شكرًا لتقييمك!",
        "rat_report": "🚩 إبلاغ", "rat_reported": "تم استلام البلاغ",
        "customers_photos": "شوف التيشرت على عملائنا 📸",
        "photos_empty": "لا توجد صور مشاركة بعد.",
        "zoom_hint": "اضغط على الصورة لتكبيرها", "img_of": "من",
        "prod_links_sz": "دليل المقاسات", "prod_links_wash": "العناية بالمنتج", "prod_links_ret": "الاستبدال",
        "szt_head": "دليل المقاسات الآسيوية", "szt_size": "المقاس", "szt_chest": "عرض الصدر",
        "szt_length": "طول التيشرت", "szt_height": "الطول المناسب", "szt_weight": "الوزن المناسب",
        "szt_cm": "سم", "szt_kg": "كغ",
        "szt_note": "ملاحظة: المقاسات الآسيوية عادةً تكون أصغر من بعض المقاسات الأوروبية. للحصول على المقاس المناسب، يُفضّل قياس تيشرت تملكه ومقارنة قياساته مع الجدول.",
        "szt_tip": "💡 نصيحة: إذا كانت قياساتك بين مقاسين، يُفضّل اختيار المقاس الأكبر للحصول على مقاس مريح، خاصة إذا كنت تفضّل المقاس الفضفاض.",
        "szt_measure": "أين أقيس؟", "szt_chest_how": "عرض الصدر", "szt_len_how": "طول التيشرت",
        "szt_width": "العرض", "szt_measure_1": "قِس عرض الصدر بوضع الشريط تحت الإبطين حول أعرض جزء في الصدر.",
        "szt_measure_2": "قِس طول التيشرت من أعلى نقطة عند الكتف حتى نهاية الحاشية السفلية.",
        "szt_between": "بين مقاسين؟",
        "szt_between_txt": "إذا وقعت قياساتك بين مقاسين، اختر الأكبر دائمًا — المقاس الفضفاض يلبس براحة أكبر.",
        "szp_title": "دليل المقاسات", "szp_sub": "جدول المقاسات الآسيوية مع طريقة القياس الصحيحة",
        "care_title": "طريقة غسل الملابس الرياضية", "care_sub": "حافظ على تيشرتك الجديد لأطول فترة ممكنة",
        "ret_page_title": "شروط الاستبدال", "ret_page_sub": "سياسة استبدال واضحة وعادلة",
        "how_page_title": "طريقة الطلب", "how_page_sub": "اطلب في 4 خطوات بسيطة",
        "prod_title": "تيشرتات الأندية", "prod_sub": "كل تيشرتات أنديتك المفضلة بمكان واحد",
        "mugs_title": "المقّات الرياضية", "mugs_sub": "مقّات فخمة لعشاق الكرة",
        "cart_page_title": "سلة الطلب", "cart_page_sub": "راجع طلبك وأكمله",
        "fav_page_title": "المفضلة", "fav_page_sub": "منتجاتك المفضلة محفوظة هنا",
        "login_page_title": "تسجيل الدخول", "login_page_sub": "ادخل برقم هاتفك لمزامنة طلباتك ونقاطك",
        "clubs_title": "اختر فريقك", "clubs_sub": "كل نادي له لون المتجر الخاص به",
        "best_title": "الأكثر مبيعًا 🔥", "best_sub": "القطع اللي الجميع يطلبها",
        "new_title": "وصل حديثًا ✨", "new_sub": "أحدث الإضافات إلى المتجر",
        "next_match": "المباراة القادمة ⚽", "next_match_sub": "شجع فريقك وارتدِ ألوانه",
        "club_shop": "تسوق منتجات الفريق", "club_products": "منتجات النادي",
        "view_all": "عرض الكل",
        "home_hero_t1": "تيشيرتك .. فريقك .. شغفك",
        "home_hero_t2": "اختر تيشيرت ناديك المفضل واطلبه الآن",
        "home_hero_sub": "تيشيرتات أصلية بأجود الخامات، وخامة رياضية مريحة تدوم معك طويلًا. سجّل دخولك واطلب في دقائق.",
        "home_cta_shop": "تسوّق الآن",
        "home_cta_team": "اختار فريقك",
        "home_cta_team_scroll": "ألوانك تبدأ من فريقك",
        "clubs_pick_title": "مين تشجع؟ 🔥",
        "clubs_pick_sub": "اختار فريقك وشوف تشكيلته.",
        "club_view_lineup": "شوف التشكيلة",
        "club_items_label": "منتجات",
        "loyal_title": "اختبر ولاءك ⚽",
        "loyal_q": "لو المباراة تبدأ الآن… مين تختار؟",
        "loyal_great": "اختيار ممتاز 🔥",
        "loyal_go": "شوف تيشرتات فريقك",
        "loyal_pick_plz": "اضغط على شعار فريقك المفضل",
        "szsec_title": "مو متأكد من مقاسك؟ 👕",
        "szsec_sub": "خلنا نساعدك تختار المقاس المناسب لك قبل الطلب.",
        "szsec_btn": "اعرف مقاسي",
        "steps_title": "طلبك أسهل مما تتخيل ⚡",
        "step_1_t": "اختار النادي والتيشرت", "step_1_d": "من تشكيلة الأندية المتوفرة",
        "step_2_t": "اختار المقاس والكمية", "step_2_d": "باستخدام دليل المقاسات",
        "step_3_t": "أرسل طلبك", "step_3_d": "عبر واتساب بضغطة واحدة",
        "step_4_t": "نجهز طلبك ونتواصل", "step_4_d": "والتوصيل حتى باب بيتك",
        "pitch_title": "مو مجرد تيشرت…",
        "pitch_title2": "هذا انتماءك ⚽",
        "pitch_btn": "ابدأ التسوق",
        "home_section_hero_tag": "GOLAZOX STADIUM",
        "atmos_skip": "تخطي",
        "ft_links": "روابط مهمة", "ft_clubs": "تشكيلة الأندية", "ft_help": "الدعم", "ft_wa": "تواصل عبر واتساب",
        "stock_left": "🔥 باقي {n} فقط", "in_stock": "متوفر الآن ✓",
        "size_oos_name": "نفد مقاس {size}", "sold_out": "SOLD OUT",
        "back_page": "← رجوع",
        "wash_title": "طريقة غسل الملابس الرياضية",
        "wash_1": "اقلب القميص من الداخل إلى الخارج.",
        "wash_2": "استخدم الماء البارد أو الفاتر فقط.",
        "wash_3": "استخدم كمية قليلة من مسحوق الغسيل اللطيف.",
        "wash_4": "يُفضّل غسله يدويًا أو باستخدام برنامج الملابس الحساسة.",
        "wash_5": "لا تستخدم المبيض (الكلور).",
        "wash_6": "اتركه يجف في مكان مظلل، وتجنب أشعة الشمس المباشرة.",
        "wash_7": "لا تقم بكي الشعارات أو الأرقام مباشرة.",
        "wash_8": "لا تنقع القميص في الماء لفترة طويلة.",
        "wash_warn": "غسل قمصان نسخة اللاعبين بالماء الساخن أو وضعها في النشافة قد يؤدي إلى تلف الشعارات أو تقشر الأرقام.",
        "ret_title": "شروط الاستبدال",
        "ret_1t": "مدة الاستبدال", "ret_1d": "يمكن استبدال المنتج خلال مدة لا تزيد عن 3 أيام من الطلب.",
        "ret_2t": "حالة المنتج", "ret_2d": "يجب الحفاظ على المنتج بحالته الأصلية، وعدم إزالة تاغ المقاس أو رمي الحلقات والكيس الرمادي الخاص بالمنتج.",
        "ret_3t": "تبديل المقاس", "ret_3d": "في حال طلب تبديل المقاس، يتم احتساب رسوم التوصيل مرة أخرى حسب رسوم التوصيل المعتمدة.",
        "ret_4t": "القطعة التالفة", "ret_4d": "في حال وصول قطعة تالفة، يكون مبلغ التوصيل على المتجر.",
        "ret_warn": "يرجى التأكد من اختيار المقاس الصحيح قبل تأكيد الطلب لتجنب رسوم التوصيل الخاصة بالاستبدال.",
        "how_title": "طريقة الطلب",
        "how_1_t": "اختر قطعتك",
        "how_2_t": "حدد المقاس",
        "how_3_t": "أضف للسلة",
        "how_4_t": "أكّد في واتساب",
        "how_5_t": "تتبع طلبك",
        "how_6_t": "قيّم وشارك",
        "how_1": "اختر القطعة التي تعجبك (تيشيرت أو مق).",
        "how_2": "حدد المقاس والكمية المطلوبة.",
        "how_3": "أضف للسلة ثم أكمل بياناتك.",
        "how_4": "أكّد الطلب في واتساب واستلم توصيلك.",
        "how_5": "تابع طلبك عبر تذكرة الطلب وميزة التتبع.",
        "how_6": "قيّم المنتج وشاركنا صورته — مكافآت وجوائز في انتظارك! 🎁",
        "how_prices_t": "أسعار واضحة وسعر ثابت للجميع",
        "how_prices_sub": "نفس السعر لكل المنتجات — بدون مفاجآت",
        "how_sec_jersey": "التيشيرتات 👕",
        "how_sec_mug": "المقّات ☕⚽",
        "how_sec_jersey_d": "سعر موحد لكل المقاسات",
        "how_sec_mug_d": "لكل التصاميم المتوفرة",
        "how_delivery_t": "التوصيل 🚚",
        "how_delivery_d": "رسوم توصيل ثابتة على كل طلب",
        "how_cta_j": "تصفح التيشيرتات",
        "how_cta_m": "تصفح المقّات",
        "how_cta_sz": "دليل المقاسات",
        "how_cta_wa": "اطلب مباشرة من واتساب",
        "contact_title": "تواصل معنا", "contact_sub": "نرد على استفساراتكم وطلباتكم على مدار اليوم.",
        "contact_wa": "تواصل عبر واتساب", "contact_num": "+973 3881 8226",
        "back": "رجوع للرئيسية",
        "quick_title": "كل ما تحتاج معرفته قبل الطلب",
        "quick_size_t": "دليل المقاسات", "quick_size_d": "اعرف مقاسك المناسب قبل الطلب",
        "quick_wash_t": "طريقة الغسيل", "quick_wash_d": "حافظ على تيشرتك لأطول فترة",
        "quick_ret_t": "شروط الاستبدال", "quick_ret_d": "تعرف على سياسة الاستبدال",
        "view_details": "عرض التفاصيل",
        "cart_title": "🛒 سلة الطلب", "cart_empty": "سلتك فارغة — أضف منتجاتك.",
        "cart_close": "إغلاق", "cart_clear": "إفراغ السلة",
        "cart_subtotal": "المجموع الفرعي", "cart_delivery": "🚚 التوصيل",
        "cart_total": "الإجمالي", "cart_checkout": "إتمام الطلب 💬",
        "cart_items": "عناصر", "pts_avail": "لديك {n} GOAL POINTS",
        "pts_use": "استخدم نقاطي", "pts_discount": "خصم نقاط",
        "co_title": "📝 بيانات الطلب", "co_name": "👤 الاسم", "co_phone": "📱 رقم الهاتف",
        "co_area": "📍 المنطقة", "co_address": "🏠 العنوان", "co_notes": "📝 ملاحظات (اختياري)",
        "co_submit": "تأكيد الطلب عبر واتساب 💬",
        "co_required": "⚠️ يرجى تعبئة الاسم والهاتف والمنطقة والعنوان.",
        "tk_title": "🏟️ تم تأكيد طلبك!", "tk_store": "GOLAZOX STADIUM",
        "tk_order": "رقم الطلب", "tk_date": "التاريخ", "tk_time": "الوقت",
        "tk_customer": "العميل", "tk_items": "المنتجات", "tk_total": "الإجمالي",
        "tk_status": "حالة الطلب", "tk_track": "تتبع طلبك 🚚",
        "tk_share": "مشاركة التذكرة 📤", "tk_save": "حفظ التذكرة 📥",
        "tk_wa": "تواصل معنا عبر واتساب 💬",
        "tk_msg": "السلام عليكم، بخصوص طلبي {code}، أود متابعة حالة الطلب.",
        "tk_issued": "🎟️ تم إصدار التذكرة!",
        "tr_title": "تتبع طلبك 🚚", "tr_code": "رقم الطلب", "tr_code_ph": "مثال: GOAL-1024",
        "tr_submit": "تتبع", "tr_notfound": "ما لقينا هذا الطلب",
        "st_pending": "تم استلام الطلب", "st_confirmed": "تم تأكيد الطلب",
        "st_preparing": "جاري التجهيز", "st_delivering": "خرج للتوصيل",
        "st_delivered": "تم التسليم", "st_cancelled": "ملغي",
        "pay_pending": "بانتظار الدفع", "pay_paid": "تم الدفع", "pay_not": "لم يتم الدفع",
        "tr_pay": "الدفع",
        "req_title": "📝 طلب منتج خاص", "req_sub": "ما لقيت اللي تبيه؟ اطلبه منا!",
        "req_club": "اسم النادي", "req_type": "نوع المنتج", "req_version": "نوع التيشيرت",
        "req_size": "المقاس", "req_qty": "الكمية", "req_notes": "ملاحظات إضافية",
        "req_send": "إرسال الطلب عبر واتساب 💬",
        "req_ok": "تم تسجيل طلبك الخاص!", "req_ref": "رقم المرجع",
        "type_jersey": "تيشيرت", "type_mug": "مق", "type_other": "منتج آخر",
        "ver_home": "Home", "ver_away": "Away", "ver_third": "Third", "ver_player": "Player Version", "ver_fan": "Fan Version",
        "pts_title": "⚽ GOAL POINTS", "pts_bal": "{n} نقطة",
        "pts_next": "أنت على بعد {n} نقطة من المكافأة القادمة",
        "pts_prog": "{cur} / {next} POINTS", "pts_history": "تاريخ النقاط",
        "pts_earn": "شراء", "pts_redeem": "استبدال النقاط", "pts_use2": "استخدم نقاطي",
        "drop_title": "إصدار جديد 🔥", "drop_coming": "جاهز للإصدار الجديد؟ ⚽🔥",
        "drop_days": "أيام", "drop_hours": "ساعات", "drop_mins": "دقائق", "drop_secs": "ثواني",
        "drop_remind": "🔔 ذكرني عند نزول الإصدار", "drop_live": "🔥 NEW DROP متوفر الآن!",
        "drop_shop": "تسوق الآن", "drop_input": "📱 رقم الهاتف", "drop_ok": "✅ تم تسجيلك!",
        "md_coming": "MATCHDAY IS COMING ⚡", "md_vs": "🆚",
        "md_starts": "المباراة تبدأ خلال", "md_d": "يوم", "md_h": "ساعة", "md_m": "دقيقة", "md_s": "ثانية",
        "md_shop": "👕 تسوق تيشرت فريقك", "md_support": "⚔️ من تشجع؟",
        "md_choice_ok": "اختيار ممتاز! ⚽", "md_your_team": "🤍 فريقك يلعب اليوم!",
        "md_cheer": "شجع فريقك 👕", "md_bar": "⚡ MATCHDAY",
        "md_live": "🔴 LIVE", "md_fulltime": "FULL TIME 🏁",
        "md_won": "🏆 Congratulations!", "md_lost": "Better luck next time 💙",
        "poll_title": "أنتم تختارون ⚽", "poll_q": "وش النادي اللي تبونه يكون متوفر عندنا بعد؟ 👀",
        "poll_vote": "🎉 تم تسجيل صوتك!", "poll_voted": "أنت ساعدتنا في اختيار المنتج القادم",
        "poll_winner": "🏆 الفائز هو...", "poll_thanks": "شكرًا لكل من شارك في التصويت!",
        "poll_hidden": "النتائج تُعلن بعد انتهاء التصويت", "poll_votes": "صوت",
        "is_title": "📷 ابحث بالصورة", "is_sub": "صوّر أو ارفع صورة للتيشيرت الذي تبحث عنه 👕",
        "is_camera": "📷 التقاط صورة", "is_upload": "🖼️ رفع صورة",
        "is_analyzing": "🔎 جاري تحليل الصورة...",
        "is_desc": "أضف وصفًا للنص (اختياري)", "is_desc_ph": "مثال: أبيه نفس هذا لكن مقاس XL",
        "is_results": "وجدنا لك هذه النتائج 👀", "is_best": "أقرب تطابق",
        "is_similar": "منتجات مشابهة", "is_sim": "{p}% مشابه",
        "is_note": "💡 النتائج مبنية على ألوان الصورة — للتطابق الدقيق أرسل لنا صورة أو وصف المنتج.",
        "is_notfound": "ما لقينا نفس التيشرت بالضبط 😕", "is_near": "لكن وجدنا لك منتجات قريبة منه",
        "is_priv": "🔐 الصورة مخصصة للبحث فقط ولا تُنشر.",
        "is_request": "ما عندنا هذا التيشرت؟ اطلبه منا 👀",
        "fav_add": "أضف للمفضلة", "fav_remove": "إزالة من المفضلة", "fav_empty": "لا توجد مفضلة بعد.",
        "footer_title": "معلومات المتجر", "footer_copy": "© 2026 golazox — جميع الحقوق محفوظة",
        "welcome_t": "أهلاً وسهلاً بك في متجرنا ⚽",
        "welcome_s": "اكتشف تشكيلة تيشرتات الأندية والمقّات الرياضية واختر القطعة المفضلة لديك.",
        "welcome_ar": "العربية", "welcome_en": "English",
        "hello": "السلام عليكم، أريد طلب ",
        "jersey_w": "تيشيرت ", "mug_w": "مق ", "size_w": "المقاس ", "qty_w": "الكمية ",
        "code_w": "رقم الطلب ", "points": "نقاط",
        "admin": "لوحة التحكم", "admin_login": "تسجيل الدخول",
        "admin_blocked_title": "غير مصرح 🚫",
        "admin_blocked_msg": "غير مصرح لك بالدخول إلى هذه الصفحة.",
        "admin_blocked_back": "رجوع للمتجر",
        "ap_add": "➕ إضافة منتج", "ap_edit": "تعديل", "ap_delete": "حذف", "ap_hide": "إخفاء", "ap_show": "إظهار",
        "ap_name_ar": "الاسم (عربي)", "ap_name_en": "الاسم (إنجليزي)", "ap_club": "النادي", "ap_noclub": "بدون نادي",
        "ap_kind": "النوع", "ap_price": "السعر (ر.س)", "ap_colors": "الألوان (2، بفواصل)", "ap_imgs": "الصور (بفواصل)",
        "ap_emoji": "الإيموجي", "ap_badges": "الشارات (new/best/offer)", "ap_stock": "المخزون (مقاس:كمية)",
        "ap_save": "💾 حفظ", "ap_cancel": "إلغاء", "ap_saved": "✅ تم حفظ المنتج.",
        "ap_deleted": "تم حذف المنتج.", "ap_new_id": "معرّف (مثال: j7)",
        "golazox": "golazox",
        "ent_enter": "دخول الملعب ←", "ent_skip": "تخطي ←", "ent_welc": "أهلاً بك في عالم GOLAZOX",
        "ent_tag": "WEAR THE PASSION. LIVE THE GAME.",
        "ok_title": "🎉 تم استلام طلبك!", "ok_wa": "تم إرسال تفاصيل طلبك إلى واتساب بنجاح.",
        "ok_ticket": "🎟️ عرض التذكرة",
        "ok_saved": "✅ تم الحفظ",        "pen_title": "⚽ عندك ركلة جزاء!", "pen_sub": "سدد ركلة واحدة واربح Goal Points.",
        "pen_go": "⚽ العب ركلة الجزاء", "pen_start": "ابدأ التحدي ⚽",
        "pen_choose": "اختر مكان التسديدة", "pen_shoot": "SHOOT ⚡",
        "pen_goal": "GOOOOOAL! 🔥", "pen_nice": "أحسنت!", "pen_plus": "🪙 +10 GOAL POINTS",
        "pen_bal": "رصيدك الحالي: {n} GOAL POINTS",
        "pen_saved": "SAVED! 🧤", "pen_saved_t": "الحارس تصدى للركلة!",
        "pen_luck": "حظ أوفر في المباراة القادمة ⚽", "pen_plus0": "Goal Points: +0",
        "pen_done": "Penalty Completed ✓", "pen_once": "🔒 محاولة واحدة فقط لكل طلب",
        "pen_track": "📦 تتبع طلبي", "pen_back": "🛍️ العودة للمتجر",
        "pen_tl": "أعلى اليسار", "pen_tc": "الوسط", "pen_tr": "أعلى اليمين",
        "pen_bl": "أسفل اليسار", "pen_br": "أسفل اليمين",
        "pen_pts": "ركلة جزاء",
        "try_title": "📸 جرّبه عليك", "try_sub": "شوف كيف ممكن يبدو التيشرت عليك 👕",
        "try_cam": "📷 التقط صورة", "try_up": "🖼️ ارفع صورة",
        "try_hint": "اختر صورة واضحة يظهر فيها الجزء العلوي من جسمك لمعاينة أفضل.",
        "try_ai": "Virtual Try-On ✨", "try_dis": "النتيجة تجربة افتراضية وقد تختلف عن الشكل الحقيقي.",
        "try_add": "🛒 أضف للسلة", "try_share": "📤 تحميل المعاينة", "try_again": "🔄 إعادة التجربة",
        "try_priv": "🔐 صورتك تُرسل فقط لخادم الذكاء الاصطناعي لمعالجة المعاينة ولا تُخزن ولا تُنشر.",
        "try_product": "👕 اختر التيشيرت", "try_loading": "⚙️ جاري تركيب المعاينة بواسطة الذكاء الاصطناعي...",
        "try_ph": "سيظهر هنا معاينة لتيشيرتك عليك بعد رفع صورتك",
        "try_done": "النتيجة ✨", "try_another": "👕 جرّب تيشيرت آخر", "try_fine": "النتيجة تجربة افتراضية وقد تختلف عن الشكل الحقيقي.",
        "try_run": "✨ جرّبه عليّ", "try_badface": "📸 نحتاج صورة أوضح لوجهك — جرّب صورة بإضاءة جيدة ووجه ظاهر.",
        "try_error": "حدث خطأ أثناء معالجة المعاينة. حاول مرة أخرى لاحقًا.",
        "try_not_configured": "خدمة المعاينة غير متاحة حاليًا، حاول لاحقًا.",
        "try_result_alt": "معاينة ارتداء تيشيرت جولازوكس",
        "rv2_design": "التصميم", "rv2_fabric": "الخامة", "rv2_quality": "الجودة", "rv2_fit": "المقاس",
        "rv2_fit_q": "كيف كان المقاس؟", "rv2_fit_s": "صغير", "rv2_fit_o": "مناسب تمامًا", "rv2_fit_w": "واسع",
        "rv2_exp": "اكتب تجربتك مع المنتج...", "rv2_ver": "✓ عملية شراء موثقة",
        "rv2_pend": "بانتظار الموافقة", "rv2_stats": "إحصائيات التقييم",
        "rv2_photo_ok": "🗸 أوافق على عرض صورتي في معرض الصور بعد موافقة الإدارة",
        "pd_title": "🔔 نبهني عند انخفاض السعر", "pd_sub": "بنخبرك إذا نزل سعر المنتج.",
        "pd_phone": "أدخل رقم هاتفك:", "pd_btn": "🔔 تفعيل التنبيه", "pd_ok": "✅ تم تفعيل التنبيه!",
        "pd_mine": "🔔 تنبيهاتي", "pd_empty": "لا توجد تنبيهات.", "pd_cancel": "إلغاء التنبيه",
        "pd_cancelled": "تم إلغاء التنبيه", "pd_waiting": "بانتظار انخفاض السعر", "pd_sent": "تم إرسال التنبيه ✓",
        "pd_now": "السعر الحالي: {p}",
        "os_title": "🏟️ ORDER STADIUM", "os_placed": "الطلب", "os_placed_s": "تم استلام طلبك بنجاح.",
        "os_prep": "التجهيز", "os_prep_s": "طلبك الآن قيد التجهيز.",
        "os_way": "التوصيل", "os_way_s": "طلبك في الطريق إليك! 🔥",
        "os_arr": "الوصول", "os_arr_s": "تم تسليم طلبك بنجاح.", "os_goal": "⚽ GOAL! 🎉",
        "os_rate": "⭐ قيّم طلبك",
        "ac_account": "حسابي", "ac_login": "تسجيل الدخول", "ac_logout": "تسجيل الخروج",
        "admin_dash": "لوحة التحكم 👑", "admin_dash_short": "لوحة التحكم",
        "auth_title": "🔐 تسجيل الدخول / إنشاء حساب",
        "auth_sub": "سجّل برقم هاتفك لتحصل على نقاطك، جوازك، تذاكرك، وإعادة الطلب بضغطة واحدة.",
        "auth_phone": "رقم الهاتف", "auth_otp_btn": "📲 استلام الرمز",
        "auth_email": "البريد الإلكتروني", "auth_email_ph": "you@example.com",
        "auth_otp_ph": "أدخل رمز التحقق", "auth_name_ph": "اسمك (اختياري)",
        "auth_verify": "✓ تأكيد", "auth_wrong": "رمز التحقق غير صحيح.", "auth_bad_phone": "رقم الهاتف غير صالح.",
        "adm_q_title": "تأكيد صلاحية الأدمن 🔐",
        "adm_q_sub": "تم التحقق من بريدك الإلكتروني. للإكمال، أجب عن سؤال الأمان أدناه للحصول على صلاحية الأدمن.",
        "adm_q_q": "أفضل شخص مين؟",
        "adm_q_ph": "اكتب الإجابة هنا",
        "adm_q_btn": "تحقق",
        "adm_q_wrong": "الإجابة غير صحيحة.",
        "adm_q_loading": "جارٍ التحقق...",
        "auth_demo_note": "وضع تجريبي: الرمز يظهر هنا (لا يوجد مزوّد SMS بعد).",
        "auth_otp_fail": "تعذّر إرسال الرمز، حاول مجددًا.",
        "auth_demo_fill": "تم تعبئة الرمز تلقائيًا في الخانة أدناه.",
        "auth_continue": "متابعة",
        "auth_sent_to": "أرسلنا رمز التحقق إلى",
        "auth_resend": "إعادة إرسال الرمز",
        "auth_change_num": "تغيير الرقم",
        "auth_loading": "جاري الإرسال…",
        "auth_verifying": "جاري التحقق…",
        "auth_sent_ok": "تم إرسال رمز جديد إلى جوالك",
        "auth_blocked": "هذا الحساب موقوف، تواصل معنا.",
        "auth_otp_short": "أدخل رمز التحقق أولًا",
        "auth_sms_fail": "تعذر إرسال الرسالة، حاول مرة أخرى",
        "auth_sms_notcfg": "خدمة الرسائل غير مهيأة في الخادم",
        "auth_rate_limit": "محاولات كثيرة، انتظر ثم أعد المحاولة",
        "auth_expired": "انتهت صلاحية الرمز، أرسل رمزًا جديدًا",
        "auth_resend_in": "إعادة الإرسال بعد {s} ثانية",
        "auth_new": "رقم جديد — سيتم إنشاء حساب تلقائيًا.",
        "auth_tab_otp": "رمز تحقق", "auth_tab_pw": "رقم + كلمة مرور",
        "auth_pw_ph": "كلمة المرور", "auth_pw_btn": "دخول", "auth_pw_wrong": "رقم الهاتف أو كلمة المرور غير صحيحة.",
        "auth_pw_set": "كلمة مرور (اختياري) — أنشئ كلمة مرور للدخول السريع",
        "auth_pw_hint": "كلمة المرور تُستخدم مع رقم هاتفك للدخول المباشر.",
        "auth_dup_pw": "هذا الحساب مسجّل بدون كلمة مرور — ادخل برمز التحقق أولًا ثم حدّثها من حسابك.",
        "admin_blocked_title": "غير مصرح 🚫",
        "admin_blocked_msg": "غير مصرح لك بالدخول إلى هذه الصفحة.",
        "admin_blocked_back": "رجوع للمتجر",
        "acc_guest": "أنت تتصفح كزائر.", "acc_login_cta": "سجّل الدخول لمزامنة طلباتك ونقاطك.",
        "acc_title": "حسابي", "acc_welcome": "أهلاً بك", "acc_member_since": "عضو منذ",
        "acc_spent": "إجمالي المشتريات", "acc_orders": "📦 طلباتي", "acc_favs": "❤️ المفضلة",
        "acc_sizes": "📏 مقاساتي المحفوظة", "acc_sizes_empty": "لا توجد مقاسات محفوظة بعد — اختر مقاساً عند الطلب وسيُحفظ تلقائياً.",
        "acc_alerts": "🔔 تنبيهاتي", "acc_points": "⭐ نقاطي", "acc_passport": "🎫 جواز كرة القدم",
        "acc_notifs": "🔔 إشعاراتي", "acc_notifs_empty": "لا توجد إشعارات بعد — سنُخبرك عند تحديث حالة طلبك.",
        "acc_dna": "🧬 بصمة كرة القدم", "acc_data": "✏️ بياناتي", "acc_settings": "⚙️ الإعدادات",
        "acc_empty_orders": "لا توجد طلبات بعد — ابدأ تسوقك!", "acc_empty_favs": "لا توجد منتجات مفضلة بعد.",
        "acc_reorder": "🔄 إعادة الطلب", "acc_view": "عرض",
        "ro_title": "🔄 إعادة الطلب", "ro_ok": "كل المنتجات متوفرة!", "ro_partial": "بعض المنتجات نفدت من المقاس المختار.",
        "ro_out": "غير متوفر", "ro_alt": "المقاسات المتوفرة", "ro_add": "إعادة الطلب", "ro_cancel": "إلغاء",
        "ro_added": "تمت إضافة المنتجات المتوفرة إلى السلة.", "ro_none": "لا يوجد أي مقاس متوفر.",
        "pp_title": "🎫 جواز كرة القدم", "pp_id": "رقم الجواز", "pp_level": "مستوى المشجع",
        "pp_stamps": "أختام الأندية", "pp_unlocked": "نادي مفتوح", "pp_none": "لم تفتح أي أندية بعد.",
        "pp_next": "الأندية المتبقية للمستوى التالي", "pp_new": "🎉 نادي جديد مفتوح!", "pp_reward": "المكافأة",
        "lv_0": "المشجع", "lv_1": "المستكشف", "lv_2": "الجامع", "lv_3": "الأسطورة",
        "tick_progress": "رحلة الطلب", "tstage_ok": "TICKET CONFIRMED", "tstage_pay": "PAYMENT CONFIRMED",
        "tstage_prep": "PREPARING", "tstage_way": "ON THE WAY", "tstage_done": "MATCH COMPLETED", "tstage_goal": "⚽ GOAL!",
        "ch_btn": "شجع فريقك ⚽", "ch_title": "CHEER MODE",
        "ch_t1": "COME ON!", "ch_t2": "LET'S GO!", "ch_t3": "GOAL! 🎉", "ch_t4": "MATCHDAY! 🔥",
        "ch_mute": "كتم الصوت", "ch_sound": "تفعيل الصوت",
        "dna_title": "🧬 بصمة كرة القدم", "dna_sub": "تحليل نشاطك الحقيقي في المتجر.",
        "dna_jersey": "عاشق القمصان", "dna_mug": "عاشق الكوب", "dna_both": "متوازن",
        "dna_club": "فريقك المفضل", "dna_size": "مقاسك الأكثر اختيارًا", "dna_level": "مستوى الجواز",
        "dna_pick": "🛒 مختار لك", "dna_empty": "تصفح المزيد وسيظهر تحليلك هنا.",
        "dna_ratio": "من مشاهداتك ومفضلاتك ومشترياتك",
    },
    "en": {
        "nav_home": "Home", "nav_jerseys": "Club Jerseys", "nav_mugs": "Mugs",
        "nav_sizes": "Size Guide", "nav_order": "How to Order", "nav_contact": "Contact Us",
        "lang_name": "عربي", "settings_btn": "Settings",
        "set_title": "⚙️ Site Settings", "set_lang": "🌐 Language", "set_theme": "🌙 Appearance",
        "theme_light": "☀️ Light", "theme_dark": "🌙 Dark", "set_font": "🔤 Font Size",
        "font_small": "A− Small", "font_med": "A Medium", "font_large": "A+ Large",
        "close": "Close",
        "badge": "Football Club Jerseys & Sports Mugs Store",
        "hero_t1": "Football Club Jerseys", "hero_t2": "& Sports Mugs",
        "hero_sub": "A premium collection of club jerseys and sports mugs at a flat fixed price — order now on WhatsApp.",
        "hero_cta_j": "Shop Jerseys", "hero_cta_m": "View Mugs",
        "sec_jerseys": "Latest Jerseys", "sec_jerseys_sub": "2025/2026 collection — sizes S to 3XL",
        "sec_mugs": "Mugs",         "sec_mugs_sub": "Only 6 BHD",
        "cat_jersey": "Club Jersey", "cat_mug": "Sports Mug",
        "view": "View Product", "add": "Add to Cart",
        "price_jersey": "7 BHD", "price_mug": "6 BHD",
        "wa_intro": "I'd like to order:",
        "sort_label": "Sort by:", "sort_new": "Newest", "sort_lo": "Price: Low to High",
        "sort_hi": "Price: High to Low", "sort_best": "Best Selling",
        "filters_btn": "Filters", "show_all": "Show all jerseys",
        "fp_title": "Filter Products", "fp_colors": "Color", "fp_cat": "Best Selling",
        "fp_club": "Club", "fp_size": "Size", "fp_more": "More +",
        "cat_best": "Best Selling", "cat_new": "New", "cat_offer": "Discounts",
        "show_results": "Show Results 🛒",
        "feat_1_t": "Fast Delivery", "feat_1_d": "To all areas of the Kingdom",
        "feat_2_t": "Secure Payment", "feat_2_d": "Multiple payment options",
        "feat_3_t": "High Quality", "feat_3_d": "100% original fabrics",
        "feat_4_t": "Exchange Guarantee", "feat_4_d": "Easy fast exchange & returns",
        "b_new": "New ✨", "b_best": "Best Seller 🔥", "b_offer": "Offer 🏷️", "b_soldout": "Sold Out",
        "search_ph": "🔍 Search club or product...",
        "filter_club": "Club", "filter_type": "Type", "filter_size": "Size",
        "filter_all": "All", "fav_filter": "❤️ Favorites", "img_search": "📷 Search by Image",
        "search_none": "We couldn't find the product you're looking for ⚽", "clear_filters": "Clear filters",
        "filter_price": "Price", "price_min": "Min", "price_max": "Max",
        "filter_avail": "Available only", "filter_apply": "Apply",
        "size_label": "Select Size", "size_guide": "Size Guide",
        "qty_label": "Quantity", "order_wa": "Order via WhatsApp",
        "size_required": "⚠️ Please select a size first.",
        "size_oos": "This size is currently unavailable.",
        "notify_me": "🔔 Notify me when available",
        "notif_title": "Size unavailable 🔔",
        "notif_sub": "Enter your phone number and we will notify you once this size is back.",
        "phone_label": "📱 Phone number", "country_label": "Country code",
        "notify_btn": "🔔 Notify me",
        "notify_ok": "✅ Your number has been registered!",
        "notify_ok2": "We will notify you when size {size} is available.",
        "stock_left": "🔥 Only {n} left", "in_stock": "In stock ✓",
        "detail_btn": "View Details 🔍",
        "trust_1": "⭐ Great rating", "trust_2": "🔥 Most wanted", "trust_3": "✓ Available now", "trust_4": "👕 Multiple sizes",
        "trust_i1": "✓ Order via WhatsApp", "trust_i2": "✓ Clear size guide",
        "trust_i3": "✓ Exchange allowed per policy", "trust_i4": "✓ Notify when size is back",
        "you_may_like": "You may also like ⚽",
        "last_order": "🔄 You ordered this before — your last size: {sz}, qty: {q}",
        "saved_size": "📏 Your saved size for this product: {sz}",
        "rat_title": "Customer Reviews ⭐", "rat_empty": "No reviews yet — be the first!",
        "rat_avg": "{avg} / 5", "rat_based": "Based on {n} reviews",
        "rat_write": "✍️ Write a review", "rat_name": "Your name", "rat_stars": "Rating",
        "rat_comment": "Your comment", "rat_photo": "📷 Photo (optional)",
        "rat_submit": "Post review", "rat_thanks": "✅ Thanks for your review!",
        "rat_report": "🚩 Report", "rat_reported": "Report received",
        "customers_photos": "See the jersey on our customers 📸",
        "photos_empty": "No shared photos yet.",
        "zoom_hint": "Tap the image to zoom", "img_of": "of",
        "prod_links_sz": "Size Guide", "prod_links_wash": "Product Care", "prod_links_ret": "Returns",
        "szt_head": "Asian Size Guide", "szt_size": "Size", "szt_chest": "Chest Width",
        "szt_length": "Jersey Length", "szt_height": "Suggested Height", "szt_weight": "Suggested Weight",
        "szt_cm": "cm", "szt_kg": "kg",
        "szt_note": "Note: Asian sizes may run smaller than European sizes. For the best fit, measure a shirt you already own and compare its measurements with our size chart.",
        "szt_tip": "Tip: For the best fit, measure a shirt you already own and compare its measurements with our size chart.",
        "szt_measure": "Where do I measure?", "szt_chest_how": "Chest Width", "szt_len_how": "Jersey Length",
        "szt_width": "Width", "szt_measure_1": "Measure chest width with the tape under your arms around the widest part of your chest.",
        "szt_measure_2": "Measure jersey length from the top of the shoulder to the bottom hem.",
        "szt_between": "Between sizes?",
        "szt_between_txt": "If your measurements fall between two sizes, always choose the larger one — a looser fit is more comfortable.",
        "szp_title": "Size Guide", "szp_sub": "Asian size chart with the correct measuring method",
        "care_title": "Caring for Sportswear", "care_sub": "Keep your new jersey in top shape for longer",
        "ret_page_title": "Returns & Exchange", "ret_page_sub": "A clear and fair exchange policy",
        "how_page_title": "How to Order", "how_page_sub": "Order in 4 simple steps",
        "prod_title": "Club Jerseys", "prod_sub": "Every favorite club jersey in one place",
        "mugs_title": "Sports Mugs", "mugs_sub": "Premium mugs for football fans",
        "cart_page_title": "Your Cart", "cart_page_sub": "Review and complete your order",
        "fav_page_title": "Favorites", "fav_page_sub": "Your favorite products live here",
        "login_page_title": "Login", "login_page_sub": "Sign in with your phone to sync orders & points",
        "clubs_title": "Choose Your Team", "clubs_sub": "Every club gives the store its own colors",
        "best_title": "Best Sellers 🔥", "best_sub": "The pieces everyone is asking for",
        "new_title": "New Arrivals ✨", "new_sub": "The latest additions to the store",
        "next_match": "Next Match ⚽", "next_match_sub": "Cheer for your team in its colors",
        "club_shop": "Shop team products", "club_products": "Club products",
        "view_all": "View all",
        "home_hero_t1": "Your jersey.. your team..",
        "home_hero_t2": "your passion ⚽",
        "home_hero_sub": "Pick your favorite club's jersey and order it now.",
        "home_cta_shop": "Shop Now",
        "home_cta_team": "Pick Your Team",
        "home_cta_team_scroll": "Your colors start with your team",
        "clubs_pick_title": "Who do you support? 🔥",
        "clubs_pick_sub": "Choose your team and see their lineup.",
        "club_view_lineup": "View lineup",
        "club_items_label": "products",
        "loyal_title": "Test Your Loyalty ⚽",
        "loyal_q": "If the match starts right now… who do you pick?",
        "loyal_great": "Great choice 🔥",
        "loyal_go": "See your team's jerseys",
        "loyal_pick_plz": "Tap your favorite team's badge",
        "szsec_title": "Not sure about your size? 👕",
        "szsec_sub": "Let us help you pick the right size before ordering.",
        "szsec_btn": "Find My Size",
        "steps_title": "Ordering is easier than you think ⚡",
        "step_1_t": "Pick the club & jersey", "step_1_d": "From the available club lineup",
        "step_2_t": "Pick the size & quantity", "step_2_d": "Using the size guide",
        "step_3_t": "Send your order", "step_3_d": "On WhatsApp in one tap",
        "step_4_t": "We prepare & contact you", "step_4_d": "Delivered right to your door",
        "pitch_title": "It's not just a jersey…",
        "pitch_title2": "it's your identity ⚽",
        "pitch_btn": "Start Shopping",
        "home_section_hero_tag": "GOLAZOX STADIUM",
        "atmos_skip": "Skip",
        "ft_links": "Quick Links", "ft_clubs": "Club Lineup", "ft_help": "Support", "ft_wa": "Chat on WhatsApp",
        "size_oos_name": "Size {size} sold out", "sold_out": "SOLD OUT",
        "back_page": "← Back",
        "wash_title": "How to Wash Sports Clothing",
        "wash_1": "Turn the shirt inside out.",
        "wash_2": "Use only cold or lukewarm water.",
        "wash_3": "Use a small amount of gentle detergent.",
        "wash_4": "Prefer hand washing or the delicate cycle.",
        "wash_5": "Do not use bleach.",
        "wash_6": "Dry in a shaded place, away from direct sunlight.",
        "wash_7": "Do not iron logos or numbers directly.",
        "wash_8": "Do not soak the shirt for a long time.",
        "wash_warn": "Washing player-version shirts in hot water or putting them in the dryer may damage the logos or peel off the numbers.",
        "ret_title": "Return Policy",
        "ret_1t": "Return period", "ret_1d": "Products can be exchanged within no more than 3 days from the order date.",
        "ret_2t": "Product condition", "ret_2d": "The product must be kept in its original condition, keeping the size tag, hangers and the grey bag, without removing them.",
        "ret_3t": "Size exchange", "ret_3d": "For size exchanges, delivery fees will be charged again according to the approved delivery fees.",
        "ret_4t": "Damaged item", "ret_4d": "If the item arrives damaged, the delivery fee is covered by the store.",
        "ret_warn": "Please make sure to choose the correct size before confirming your order to avoid exchange delivery fees.",
        "how_title": "How to Order",
        "how_1_t": "Pick your piece",
        "how_2_t": "Pick the size",
        "how_3_t": "Add to cart",
        "how_4_t": "Confirm on WhatsApp",
        "how_5_t": "Track your order",
        "how_6_t": "Review & share",
        "how_1": "Choose the piece you like (jersey or mug).",
        "how_2": "Select the size and quantity.",
        "how_3": "Add to cart and complete your details.",
        "how_4": "Confirm the order on WhatsApp and receive your delivery.",
        "how_5": "Track your order via the order ticket and tracking feature.",
        "how_6": "Review the product and share your photo — rewards and prizes await! 🎁",
        "how_prices_t": "Clear pricing, one fixed price for all",
        "how_prices_sub": "The same price for every product — no surprises",
        "how_sec_jersey": "Jerseys 👕",
        "how_sec_mug": "Mugs ☕⚽",
        "how_sec_jersey_d": "One fixed price for every size",
        "how_sec_mug_d": "Across all available designs",
        "how_delivery_t": "Delivery 🚚",
        "how_delivery_d": "A flat delivery fee on every order",
        "how_cta_j": "Browse jerseys",
        "how_cta_m": "Browse mugs",
        "how_cta_sz": "Size guide",
        "how_cta_wa": "Order directly on WhatsApp",
        "contact_title": "Contact Us", "contact_sub": "We respond to your questions and orders all day long.",
        "contact_wa": "Chat on WhatsApp", "contact_num": "+973 3881 8226",
        "back": "Back to Home",
        "quick_title": "Everything you need to know before ordering",
        "quick_size_t": "Size Guide", "quick_size_d": "Find your perfect fit",
        "quick_wash_t": "Washing Method", "quick_wash_d": "Keep your jersey for longer",
        "quick_ret_t": "Return Policy", "quick_ret_d": "Learn about our return policy",
        "view_details": "View Details",
        "cart_title": "🛒 Your Cart", "cart_empty": "Your cart is empty — add some products.",
        "cart_close": "Close", "cart_clear": "Clear cart",
        "cart_subtotal": "Subtotal", "cart_delivery": "🚚 Delivery",
        "cart_total": "Total", "cart_checkout": "Checkout 💬",
        "cart_items": "items", "pts_avail": "You have {n} GOAL POINTS",
        "pts_use": "Use my points", "pts_discount": "Points discount",
        "co_title": "📝 Order Details", "co_name": "👤 Name", "co_phone": "📱 Phone",
        "co_area": "📍 Area", "co_address": "🏠 Address", "co_notes": "📝 Notes (optional)",
        "co_submit": "Confirm order via WhatsApp 💬",
        "co_required": "⚠️ Please fill name, phone, area and address.",
        "tk_title": "🏟️ Order Confirmed!", "tk_store": "GOLAZOX STADIUM",
        "tk_order": "Order Number", "tk_date": "Date", "tk_time": "Time",
        "tk_customer": "Customer", "tk_items": "Items", "tk_total": "Total",
        "tk_status": "Order Status", "tk_track": "Track your order 🚚",
        "tk_share": "Share ticket 📤", "tk_save": "Save ticket 📥",
        "tk_wa": "Contact us on WhatsApp 💬",
        "tk_msg": "Hello, regarding my order {code}, I would like to check the order status.",
        "tk_issued": "🎟️ Ticket Issued!",
        "tr_title": "Track your order 🚚", "tr_code": "Order number", "tr_code_ph": "e.g. GOAL-1024",
        "tr_submit": "Track", "tr_notfound": "Order not found",
        "st_pending": "Order received", "st_confirmed": "Confirmed",
        "st_preparing": "Preparing", "st_delivering": "Out for delivery",
        "st_delivered": "Delivered", "st_cancelled": "Cancelled",
        "pay_pending": "Awaiting payment", "pay_paid": "Paid", "pay_not": "Not paid",
        "tr_pay": "Payment",
        "req_title": "📝 Request a Product", "req_sub": "Can't find what you need? Request it!",
        "req_club": "Club name", "req_type": "Product type", "req_version": "Jersey type",
        "req_size": "Size", "req_qty": "Quantity", "req_notes": "Extra notes",
        "req_send": "Send request via WhatsApp 💬",
        "req_ok": "Your special request has been registered!", "req_ref": "Reference",
        "type_jersey": "Jersey", "type_mug": "Mug", "type_other": "Other",
        "ver_home": "Home", "ver_away": "Away", "ver_third": "Third", "ver_player": "Player Version", "ver_fan": "Fan Version",
        "pts_title": "⚽ GOAL POINTS", "pts_bal": "{n} points",
        "pts_next": "You are {n} points away from the next reward",
        "pts_prog": "{cur} / {next} POINTS", "pts_history": "Points history",
        "pts_earn": "Purchase", "pts_redeem": "Points redeemed", "pts_use2": "Use my points",
        "drop_title": "New Drop 🔥", "drop_coming": "Ready for the new drop? ⚽🔥",
        "drop_days": "days", "drop_hours": "hrs", "drop_mins": "min", "drop_secs": "sec",
        "drop_remind": "🔔 Remind me", "drop_live": "🔥 NEW DROP AVAILABLE NOW!",
        "drop_shop": "Shop now", "drop_input": "📱 Phone number", "drop_ok": "✅ Registered!",
        "md_coming": "MATCHDAY IS COMING ⚡", "md_vs": "🆚",
        "md_starts": "Match starts in", "md_d": "day", "md_h": "hr", "md_m": "min", "md_s": "sec",
        "md_shop": "👕 Shop your team's jersey", "md_support": "⚔️ Who are you supporting?",
        "md_choice_ok": "Great choice! ⚽", "md_your_team": "🤍 Your team plays today!",
        "md_cheer": "Cheer for your team 👕", "md_bar": "⚡ MATCHDAY",
        "md_live": "🔴 LIVE", "md_fulltime": "FULL TIME 🏁",
        "md_won": "🏆 Congratulations!", "md_lost": "Better luck next time 💙",
        "poll_title": "YOU CHOOSE ⚽", "poll_q": "Which club should we add next? 👀",
        "poll_vote": "🎉 Your vote has been recorded!", "poll_voted": "You helped us choose the next product",
        "poll_winner": "🏆 The winner is...", "poll_thanks": "Thanks to everyone who voted!",
        "poll_hidden": "Results will be announced when voting ends", "poll_votes": "votes",
        "is_title": "📷 Search by Image", "is_sub": "Take or upload a photo of the jersey you're looking for 👕",
        "is_camera": "📷 Take photo", "is_upload": "🖼️ Upload photo",
        "is_analyzing": "🔎 Analyzing image...",
        "is_desc": "Add a text description (optional)", "is_desc_ph": "e.g. Same but size XL",
        "is_results": "Here are your results 👀", "is_best": "Closest match",
        "is_similar": "Similar products", "is_sim": "{p}% similar",
        "is_note": "💡 Results are based on image colors — for an exact match send us a photo or product description.",
        "is_notfound": "We didn't find that exact jersey 😕", "is_near": "But here are similar products",
        "is_priv": "🔐 Your image is only used for the search and is never published.",
        "is_request": "Don't have this jersey? Request it 👀",
        "fav_add": "Add to favorites", "fav_remove": "Remove from favorites", "fav_empty": "No favorites yet.",
        "footer_title": "Store Info", "footer_copy": "© 2026 golazox — All rights reserved",
        "welcome_t": "Welcome to our store ⚽",
        "welcome_s": "Discover our collection of football club jerseys and sports mugs and find your favorite piece.",
        "welcome_ar": "العربية", "welcome_en": "English",
        "hello": "Hello, I would like to order ",
        "jersey_w": "jersey ", "mug_w": "mug ", "size_w": "size ", "qty_w": "quantity ",
        "code_w": "Order ", "points": "points",
        "admin": "Admin", "admin_login": "Log in",
        "admin_blocked_title": "Not Allowed 🚫",
        "admin_blocked_msg": "You are not allowed to access this page.",
        "admin_blocked_back": "Back to store",
        "ap_add": "➕ Add product", "ap_edit": "Edit", "ap_delete": "Delete", "ap_hide": "Hide", "ap_show": "Show",
        "ap_name_ar": "Name (Arabic)", "ap_name_en": "Name (English)", "ap_club": "Club", "ap_noclub": "No club",
        "ap_kind": "Type", "ap_price": "Price (SAR)", "ap_colors": "Colors (2, comma-separated)", "ap_imgs": "Images (comma-separated)",
        "ap_emoji": "Emoji", "ap_badges": "Badges (new/best/offer)", "ap_stock": "Stock (size:qty)",
        "ap_save": "💾 Save", "ap_cancel": "Cancel", "ap_saved": "✅ Product saved.",
        "ap_deleted": "Product deleted.", "ap_new_id": "ID (e.g. j7)",
        "golazox": "golazox",
        "ent_enter": "Enter the Stadium →", "ent_skip": "Skip →", "ent_welc": "WELCOME TO THE GAME",
        "ent_tag": "WEAR THE PASSION. LIVE THE GAME.",
        "ok_title": "🎉 Order received!", "ok_wa": "Your order details were sent to WhatsApp successfully.",
        "ok_ticket": "🎟️ View ticket",
        "ok_saved": "✅ Saved",
        "pen_title": "⚽ Penalty Challenge!", "pen_sub": "Take one shot and win Goal Points.",
        "pen_go": "⚽ Play the penalty", "pen_start": "Start the Challenge ⚽",
        "pen_choose": "Choose your shot", "pen_shoot": "SHOOT ⚡",
        "pen_goal": "GOOOOOAL! 🔥", "pen_nice": "Well done!", "pen_plus": "🪙 +10 GOAL POINTS",
        "pen_bal": "Your balance: {n} GOAL POINTS",
        "pen_saved": "SAVED! 🧤", "pen_saved_t": "The keeper saved it!",
        "pen_luck": "Better luck next match ⚽", "pen_plus0": "Goal Points: +0",
        "pen_done": "Penalty Completed ✓", "pen_once": "🔒 One attempt per order",
        "pen_track": "📦 Track my order", "pen_back": "🛍️ Back to store",
        "pen_tl": "Top Left", "pen_tc": "Center", "pen_tr": "Top Right",
        "pen_bl": "Bottom Left", "pen_br": "Bottom Right",
        "pen_pts": "Penalty",
        "try_title": "📸 Try It On", "try_sub": "See how this jersey might look on you 👕",
        "try_cam": "📷 Take a photo", "try_up": "🖼️ Upload a photo",
        "try_hint": "Pick a clear photo showing your upper body for a better preview.",
        "try_ai": "AI Preview ✨", "try_dis": "This is an approximate preview only and does not represent the exact fit or final look.",
        "try_add": "🛒 Add to cart", "try_share": "📤 Share preview", "try_again": "🔄 Try another photo",
        "try_priv": "🔐 Your photo is used only for the preview on your device and is never uploaded or published.",
        "try_product": "👕 Choose the jersey", "try_loading": "Preparing the preview...",
        "rv2_design": "Design", "rv2_fabric": "Fabric", "rv2_quality": "Quality", "rv2_fit": "Fit",
        "rv2_fit_q": "How was the fit?", "rv2_fit_s": "Small", "rv2_fit_o": "Fits perfectly", "rv2_fit_w": "Wide",
        "rv2_exp": "Write your experience with the product...", "rv2_ver": "✓ Verified Purchase",
        "rv2_pend": "Pending approval", "rv2_stats": "Rating breakdown",
        "rv2_photo_ok": "🗸 I agree to my photo being shown in the gallery (subject to admin approval)",
        "pd_title": "🔔 Price Drop Alert", "pd_sub": "We'll let you know if the price drops.",
        "pd_phone": "Enter your phone number:", "pd_btn": "🔔 Enable alert", "pd_ok": "✅ Alert enabled!",
        "pd_mine": "🔔 My Price Alerts", "pd_empty": "No alerts yet.", "pd_cancel": "Cancel alert",
        "pd_cancelled": "Alert cancelled", "pd_waiting": "Waiting for price drop", "pd_sent": "Alert sent ✓",
        "pd_now": "Current price: {p}",
        "os_title": "🏟️ ORDER STADIUM", "os_placed": "ORDER PLACED", "os_placed_s": "Your order was received successfully.",
        "os_prep": "BEING PREPARED", "os_prep_s": "Your order is being prepared.",
        "os_way": "ON THE WAY", "os_way_s": "Your order is on its way! 🔥",
        "os_arr": "DELIVERED", "os_arr_s": "Your order was delivered successfully.", "os_goal": "⚽ GOAL! 🎉",
        "os_rate": "⭐ Rate your order",
        "ac_account": "My Account", "ac_login": "Sign in", "ac_logout": "Sign out",
        "admin_dash": "Admin Panel 👑", "admin_dash_short": "Admin Panel",
        "auth_title": "🔐 Sign in / Create account",
        "auth_sub": "Sign in with your phone to keep your points, passport, tickets and one-tap re-order.",
        "auth_phone": "Phone number", "auth_otp_btn": "📲 Get code",
        "auth_email": "Email address", "auth_email_ph": "you@example.com",
        "auth_otp_ph": "Enter the verification code", "auth_name_ph": "Your name (optional)",
        "auth_verify": "✓ Confirm", "auth_wrong": "Wrong verification code.", "auth_bad_phone": "Invalid phone number.",
        "adm_q_title": "Admin Verification 🔐",
        "adm_q_sub": "Your email is verified. To continue, answer the security question below to get admin access.",
        "adm_q_q": "أفضل شخص مين؟",
        "adm_q_ph": "Type the answer here",
        "adm_q_btn": "Verify",
        "adm_q_wrong": "Wrong answer.",
        "adm_q_loading": "Verifying...",
        "auth_demo_note": "Demo mode: the code is shown here (no SMS provider configured yet).",
        "auth_otp_fail": "Could not send the code, try again.",
        "auth_demo_fill": "The code was filled in automatically below.",
        "auth_continue": "Continue",
        "auth_sent_to": "We sent a verification code to",
        "auth_resend": "Resend code",
        "auth_change_num": "Change number",
        "auth_loading": "Sending…",
        "auth_verifying": "Verifying…",
        "auth_sent_ok": "A new code was sent to your phone",
        "auth_blocked": "This account is blocked. Contact us.",
        "auth_otp_short": "Enter the verification code first",
        "auth_sms_fail": "Could not send the SMS, please try again",
        "auth_sms_notcfg": "SMS service is not configured on the server",
        "auth_rate_limit": "Too many attempts, try again later",
        "auth_expired": "The code expired, request a new one",
        "auth_resend_in": "Resend in {s}s",
        "auth_tab_otp": "Verification code", "auth_tab_pw": "Phone + password",
        "auth_pw_ph": "Password", "auth_pw_btn": "Sign in", "auth_pw_wrong": "Wrong phone number or password.",
        "auth_pw_set": "Password (optional) — set a password for quick sign-in",
        "auth_pw_hint": "The password is used with your phone number for direct sign-in.",
        "auth_dup_pw": "This account has no password set — sign in with a code first, then update it in your account.",
        "admin_blocked_title": "Not Allowed 🚫",
        "admin_blocked_msg": "You are not allowed to access this page.",
        "admin_blocked_back": "Back to store",
        "auth_new": "New number — an account will be created automatically.",
        "acc_guest": "You are browsing as a guest.", "acc_login_cta": "Sign in to sync your orders and points.",
        "acc_title": "My Account", "acc_welcome": "Welcome", "acc_member_since": "Member since",
        "acc_spent": "Total spent", "acc_orders": "📦 My Orders", "acc_favs": "❤️ Favorites",
        "acc_sizes": "📏 My Saved Sizes", "acc_sizes_empty": "No saved sizes yet — pick a size when ordering and it will be saved automatically.",
        "acc_alerts": "🔔 My Alerts", "acc_points": "⭐ My Points", "acc_passport": "🎫 Football Passport",
        "acc_notifs": "🔔 My Notifications", "acc_notifs_empty": "No notifications yet — we'll let you know when your order status changes.",
        "acc_dna": "🧬 Football DNA", "acc_data": "✏️ My Details", "acc_settings": "⚙️ Settings",
        "acc_empty_orders": "No orders yet — start shopping!", "acc_empty_favs": "No favorites yet.",
        "acc_reorder": "🔄 Re-order", "acc_view": "View",
        "ro_title": "🔄 Re-order", "ro_ok": "Everything is in stock!", "ro_partial": "Some items are out of the chosen size.",
        "ro_out": "Unavailable", "ro_alt": "Available sizes", "ro_add": "Re-order", "ro_cancel": "Cancel",
        "ro_added": "Available items were added to your cart.", "ro_none": "No size available at all.",
        "pp_title": "🎫 Football Passport", "pp_id": "Passport ID", "pp_level": "Fan level",
        "pp_stamps": "Club stamps", "pp_unlocked": "club unlocked", "pp_none": "No clubs unlocked yet.",
        "pp_next": "clubs left for the next level", "pp_new": "🎉 New club unlocked!", "pp_reward": "Reward",
        "lv_0": "Tourist", "lv_1": "Explorer", "lv_2": "Collector", "lv_3": "Legend",
        "tick_progress": "Order journey", "tstage_ok": "TICKET CONFIRMED", "tstage_pay": "PAYMENT CONFIRMED",
        "tstage_prep": "PREPARING", "tstage_way": "ON THE WAY", "tstage_done": "MATCH COMPLETED", "tstage_goal": "⚽ GOAL!",
        "ch_btn": "Cheer your team ⚽", "ch_title": "CHEER MODE",
        "ch_t1": "COME ON!", "ch_t2": "LET'S GO!", "ch_t3": "GOAL! 🎉", "ch_t4": "MATCHDAY! 🔥",
        "ch_mute": "Mute", "ch_sound": "Sound on",
        "dna_title": "🧬 Football DNA", "dna_sub": "Analysed from your real activity in the store.",
        "dna_jersey": "Jersey lover", "dna_mug": "Mug lover", "dna_both": "Balanced",
        "dna_club": "Your favourite club", "dna_size": "Most chosen size", "dna_level": "Passport level",
        "dna_pick": "🛒 Picked for you", "dna_empty": "Browse more and your analysis will appear here.",
        "dna_ratio": "from your views, favorites and purchases",
    },
}


def product_name(p, en):
    return p.get("name_en" if en else "name_ar", "")


def club_of(p):
    return CLUBS.get(p.get("club_id"))


def club_name(p, en):
    c = club_of(p)
    return c.get("en" if en else "ar") if c else ""
